@token = {{login.response.body.token}}


### создание файла
GET http://localhost:5001/createFile

###
GET http://localhost:5001/readFile

###
POST http://localhost:5001/createTask
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "test",
    "completed": true,
    "description": "refr"
}

### удаление файла
DELETE  http://localhost:5001/deleteFile

### апдейт таски
PUT  http://localhost:5001/updateTask/6a707366e2706f0017494c11
Content-Type: application/json
accept: application/json
Authorization: Bearer {{token}}

{
    "title": "erferf"
}

### комплитед таски

PATCH http://localhost:5001/updateTask/6a6ee0ecb4bb9f68bc41c84a
Content-Type: application/json
Authorization: Bearer {{token}}


### удалить таску

DELETE http://localhost:5001/deleteTask/6a707365e2706f0017494c10
Content-Type: application/json
Authorization: Bearer {{token}}

### получить таску

GET  http://localhost:5001/getTodo/6a707365e2706f0017494c10
Content-Type: application/json
Authorization: Bearer {{token}}

### получить все таски пользователя

GET  http://localhost:5001/getTodo
Content-Type: application/json
Authorization: Bearer {{token}}


### получить выполненные таски

GET  http://localhost:5001/getTodo/?completed=false
Content-Type: application/json
Authorization: Bearer {{token}}


### регистрация

POST  http://localhost:5001/registration
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345678",
    "name": "Kristina"
}

### логин
# @name login
POST  http://localhost:5001/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345678"
}